export type RailStation = { code: string; name: string };

/** Frequently used stations for instant (offline) suggestions. */
export const POPULAR_STATIONS: RailStation[] = [
  { code: "DBG", name: "Darbhanga Jn" },
  { code: "LSI", name: "Laheria Sarai" },
  { code: "SKI", name: "Sakri Jn" },
  { code: "MBI", name: "Madhubani" },
  { code: "JYG", name: "Jaynagar" },
  { code: "SPJ", name: "Samastipur Jn" },
  { code: "MFP", name: "Muzaffarpur Jn" },
  { code: "HJP", name: "Hajipur Jn" },
  { code: "SEE", name: "Sonpur Jn" },
  { code: "PNBE", name: "Patna Jn" },
  { code: "PPTA", name: "Patliputra Jn" },
  { code: "RJPB", name: "Rajendra Nagar T" },
  { code: "DNR", name: "Danapur" },
  { code: "BJU", name: "Barauni Jn" },
  { code: "BGP", name: "Bhagalpur" },
  { code: "JMU", name: "Jamalpur Jn" },
  { code: "KIR", name: "Katihar Jn" },
  { code: "SHC", name: "Saharsa Jn" },
  { code: "MKA", name: "Mokama" },
  { code: "GAYA", name: "Gaya Jn" },
  { code: "DDU", name: "Pt DD Upadhyaya Jn" },
  { code: "BSB", name: "Varanasi Jn" },
  { code: "LKO", name: "Lucknow Charbagh" },
  { code: "CNB", name: "Kanpur Central" },
  { code: "PRYJ", name: "Prayagraj Jn" },
  { code: "NDLS", name: "New Delhi" },
  { code: "DLI", name: "Delhi Jn" },
  { code: "ANVT", name: "Anand Vihar Terminal" },
  { code: "NZM", name: "Hazrat Nizamuddin" },
  { code: "GZB", name: "Ghaziabad" },
  { code: "HWH", name: "Howrah Jn" },
  { code: "SDAH", name: "Sealdah" },
  { code: "KOAA", name: "Kolkata" },
  { code: "MAS", name: "MGR Chennai Central" },
  { code: "CSMT", name: "Mumbai CSMT" },
  { code: "MMCT", name: "Mumbai Central" },
  { code: "LTT", name: "Lokmanya Tilak T" },
  { code: "BDTS", name: "Bandra Terminus" },
  { code: "PUNE", name: "Pune Jn" },
  { code: "ADI", name: "Ahmedabad Jn" },
  { code: "ST", name: "Surat" },
  { code: "JP", name: "Jaipur Jn" },
  { code: "BPL", name: "Bhopal Jn" },
  { code: "NGP", name: "Nagpur Jn" },
  { code: "SBC", name: "KSR Bengaluru" },
  { code: "SC", name: "Secunderabad Jn" },
  { code: "HYB", name: "Hyderabad Deccan" },
  { code: "TVC", name: "Thiruvananthapuram" },
  { code: "ERS", name: "Ernakulam Jn" },
  { code: "BBS", name: "Bhubaneswar" },
  { code: "GHY", name: "Guwahati" },
  { code: "NJP", name: "New Jalpaiguri" },
  { code: "RNC", name: "Ranchi" },
  { code: "TATA", name: "Tatanagar Jn" },
  { code: "ASN", name: "Asansol Jn" },
  { code: "DHN", name: "Dhanbad Jn" },
  { code: "JAT", name: "Jammu Tawi" },
  { code: "ASR", name: "Amritsar Jn" },
  { code: "CDG", name: "Chandigarh" },
  { code: "DDN", name: "Dehradun" },
  { code: "GKP", name: "Gorakhpur Jn" },
  { code: "RXL", name: "Raxaul Jn" },
  { code: "NKE", name: "Narkatiaganj Jn" },
  { code: "FBG", name: "Forbesganj" },
];

/** Trains that run through the Darbhanga / Mithila belt, for instant number+name hints. */
export const POPULAR_TRAINS: { number: string; name: string }[] = [
  { number: "12565", name: "Bihar Sampark Kranti Exp" },
  { number: "12566", name: "Bihar Sampark Kranti Exp" },
  { number: "12561", name: "Swatantrata Senani Exp" },
  { number: "12562", name: "Swatantrata Senani Exp" },
  { number: "12557", name: "Sapt Kranti Exp" },
  { number: "12558", name: "Sapt Kranti Exp" },
  { number: "12553", name: "Vaishali Exp" },
  { number: "12554", name: "Vaishali Exp" },
  { number: "12435", name: "Garib Rath Exp" },
  { number: "12436", name: "Garib Rath Exp" },
  { number: "15273", name: "Satyagrah Exp" },
  { number: "15274", name: "Satyagrah Exp" },
  { number: "19165", name: "Sabarmati Exp" },
  { number: "19166", name: "Sabarmati Exp" },
  { number: "15707", name: "Amrapali Exp" },
  { number: "13021", name: "Mithila Exp" },
  { number: "13022", name: "Mithila Exp" },
  { number: "12567", name: "Rajyarani Exp" },
  { number: "12487", name: "Seemanchal Exp" },
  { number: "12203", name: "Garib Rath Exp" },
  { number: "12791", name: "Danapur Exp" },
  { number: "12335", name: "Bhagalpur Exp" },
  { number: "12309", name: "Rajdhani Exp" },
  { number: "12301", name: "Howrah Rajdhani Exp" },
  { number: "12951", name: "Mumbai Rajdhani Exp" },
  { number: "22913", name: "Humsafar Exp" },
];
